{
 "title": "Bareos Backups",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(bareos_last_job_bytes_saved,instance)"
    }
   },
   {
    "name": "jobname",
    "label": "Backup job",
    "query": "label_values(bareos_bytes_saved, jobname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Scheduler - $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Unterminated backup jobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(bareos_last_job_status{status=\"C\", last_selector=\"last\", instance=~\"$instance\", jobname=~\"$jobname\" })",
     "legendFormat": "Created jobs"
    },
    {
     "expr": "sum(bareos_last_job_status{status=~\"R|L|l|a|i\", last_selector=\"last\", instance=~\"$instance\", jobname=~\"$jobname\"})",
     "legendFormat": "Running jobs"
    },
    {
     "expr": "sum(bareos_last_job_status{status=~\"q|F|S|m|M|s|j|c|d|p\", last_selector=\"last\", instance=~\"$instance\"})",
     "legendFormat": "Waiting jobs"
    }
   ]
  },
  {
   "title": "Backup errors and warnings",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(bareos_last_job_status{status=~\"E|f\",last_selector=\"last\", instance=~\"$instance\", jobname=~\"$jobname\"}) by(jobname)",
     "legendFormat": "Errors {{ jobname }}"
    },
    {
     "expr": "sum(bareos_last_job_status{status=~ \"W|e\",last_selector=\"last\", instance=~\"$instance\", jobname=~\"$jobname\"}) by (jobname)",
     "legendFormat": "Warnings {{ jobname }}"
    }
   ]
  },
  {
   "title": "Time since last scheduled backup",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - max(bareos_last_job_start_unix_timestamp{jobname=~\"$jobname\",jobtype=\"B\", last_selector=\"last_successful\", instance=~\"$instance\"}) by (jobname)  + 60*60",
     "legendFormat": "{{ backupjob }}"
    }
   ]
  },
  {
   "title": "Stored data summary - $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Stored data per client",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bareos_bytes_saved{jobtype=\"B\", jobname=~\"$jobname\", instance=~\"$instance\"}) by (client)",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "Stored files per client",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bareos_files_saved{jobtype=\"B\", instance=~\"$instance\", jobname=~\"$jobname\"}) by (client)",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "Stored data per job",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bareos_bytes_saved{jobtype=\"B\", instance=~\"$instance\", jobname=~\"$jobname\"}) by (jobname)",
     "legendFormat": "{{ jobname }}"
    }
   ]
  },
  {
   "title": "Stored files per job",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bareos_files_saved{jobtype=\"B\", instance=~\"$instance\", jobname=~\"$jobname\"}) by (jobname)",
     "legendFormat": "{{ jobname }}"
    }
   ]
  },
  {
   "title": "Stored data details - $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "All backed up data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "bareos_bytes_saved{jobname=~\"$jobname\", jobtype=\"B\", instance=~\"$instance\"} > 0",
     "legendFormat": "Bytes {{ jobname }}"
    },
    {
     "expr": "bareos_files_saved{jobname=~\"$jobname\", jobtype=\"B\", instance=~\"$instance\"} > 0",
     "legendFormat": "Files {{ jobname }}"
    }
   ]
  },
  {
   "title": "Backed up data ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "bareos_last_job_bytes_saved{jobname=~\"$jobname\",jobtype=\"B\", last_selector=\"last_successful\", instance=~\"$instance\"}",
     "legendFormat": "Bytes {{ jobname }}"
    }
   ]
  },
  {
   "title": "Backed up data (last full backup)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "bareos_last_job_bytes_saved{jobname=~\"$jobname\", jobtype=\"B\", last_selector=\"last_successful_full\", instance=~\"$instance\"}",
     "legendFormat": "Bytes {{ jobname }}"
    },
    {
     "expr": "bareos_last_job_files_saved{jobname=~\"$jobname\", jobtype=\"B\", last_selector=\"last_successful_full\", instance=~\"$instance\"}",
     "legendFormat": "Files {{ jobname }}"
    }
   ]
  },
  {
   "title": "Backed up data - files",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "bareos_last_job_files_saved{jobname=~\"$jobname\",jobtype=\"B\", last_selector=\"last_successful\", instance=~\"$instance\"}",
     "legendFormat": "Files {{ jobname }}"
    }
   ]
  },
  {
   "title": "Storage Pools - $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Pool status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bareos_pool_bytes{expired=\"false\", prunable=\"false\", instance=~\"$instance\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(bareos_pool_bytes{expired=\"true\",prunable=\"false\", instance=~\"$instance\"})",
     "legendFormat": "Expired"
    },
    {
     "expr": "sum(bareos_pool_bytes{prunable=\"true\"})",
     "legendFormat": "Prunable"
    }
   ]
  },
  {
   "title": "Pool wasted space",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (bareos_pool_bytes{expired=\"false\", prunable=\"false\", instance=~\"$instance\"} / on(pool) sum(bareos_pool_bytes{instance=~\"$instance\"}) by(pool))",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Stored data per pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(bareos_pool_bytes{prunable=\"false\", expired=\"false\", instance=~\"$instance\"}) by(pool)",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Prunable/expired stored data per pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(bareos_pool_bytes{prunable=\"true\", instance=~\"$instance\"}) by(pool) + sum(bareos_pool_bytes{prunable=\"false\", expired=\"true\", instance=~\"$instance\"}) by (pool)",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Volumes per pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(bareos_pool_volumes{prunable=\"false\", expired=\"false\", instance=~\"$instance\"}) by(pool)",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Prunable/expired volumes per pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(bareos_pool_volumes{prunable=\"true\", instance=~\"$instance\"}) by(pool) + sum(bareos_pool_volumes{prunable=\"false\", expired=\"true\", instance=~\"$instance\"}) by (pool)",
     "legendFormat": "{{ pool }}"
    }
   ]
  }
 ]
}